DROP DATABASE IF EXISTS hotel_db;
CREATE DATABASE hotel_db;

\c hotel_db;

CREATE TABLE guests (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL
);

CREATE TABLE rooms (
	id SERIAL PRIMARY KEY,
	room_num VARCHAR(255) NOT NULL,
	capacity FLOAT NOT NULL
);

CREATE TABLE bookings (
	id SERIAL PRIMARY KEY,
  room_id INTEGER NOT NULL,
	guest_id INTEGER NOT NULL,
	check_in DATE NOT NULL,
	check_out DATE NOT NULL
);
